### PR TITLE
Fix compilation fails due codenarc rules specifics

### PR DESCRIPTION
**Pull request by kortov**
1) codenarc couldn't resolve external dependencies (enhanced.xml rules)
2) fix some violation of codenarc rules
3) remove JUnit rules because of absence of JUnit in the project
4) add java plugin for easier ide support of the project

### CODE REVIEW

**Comment by jameskleeh** [comment]
Thanks!

**Comment by kortov** [comment]
@jameskleeh thank you for your lib, by any chance do you know when the fix will be available on maven?

**Comment by kortov** [comment]
closes #26

**Comment by jameskleeh** [comment]
@kortov Should be available shortly, if not right now

**Pull request merged**
